# Generated by Django 4.2 on 2023-04-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('estoque', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_produto', models.PositiveIntegerField()),
                ('price_produto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almoxarifado.entrada')),
                ('produto_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_entrada', to='almoxarifado.produto')),
            ],
        ),
    ]
