# Generated by Django 4.2 on 2023-04-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0002_alter_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='number',
            field=models.CharField(default='SEM NOTA', max_length=255),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item_entrada',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_item', to='almoxarifado.entrada'),
        ),
        migrations.AlterField(
            model_name='item_entrada',
            name='price_produto',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item_entrada',
            name='produto_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_item', to='almoxarifado.produto'),
        ),
    ]
