# Generated by Django 4.2 on 2023-04-09 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_produto', models.PositiveIntegerField()),
                ('price_produto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('produto_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produto_saida', to='almoxarifado.produto')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saida_item', to='almoxarifado.saida')),
            ],
        ),
    ]
