# Generated by Django 4.2 on 2023-04-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_item_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_saida',
            name='price_produto',
        ),
    ]
