# Generated by Django 4.2 on 2023-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0006_remove_item_saida_price_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='number',
            field=models.CharField(max_length=255),
        ),
    ]
