# Generated by Django 4.2 on 2023-04-09 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_produto_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_anterior',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
